### ISSUE TITLE
can debug in simulator, xcode 6.1.1 macosx 10.10

### ISSUE THREAD

**Issue by rexzhang** [clowwindy/iOS-Python-Project#4]
Traceback (most recent call last):
  File "../../build/python/ios-simulator/lib/python2.7/site.py", line 553, in <module>
  File "../../build/python/ios-simulator/lib/python2.7/site.py", line 535, in main
  File "../../build/python/ios-simulator/lib/python2.7/site.py", line 268, in addusersitepackages
  File "../../build/python/ios-simulator/lib/python2.7/site.py", line 243, in getusersitepackages
  File "../../build/python/ios-simulator/lib/python2.7/site.py", line 233, in getuserbase
  File "../../build/python/ios-simulator/lib/python2.7/sysconfig.py", line 535, in get_config_var
  File "../../build/python/ios-simulator/lib/python2.7/sysconfig.py", line 434, in get_config_vars
  File "../../build/python/ios-simulator/lib/python2.7/sysconfig.py", line 287, in _init_posix
IOError: invalid Python installation: unable to open /Users/rex/Library/Developer/CoreSimulator/Devices/05878E8D-F67B-4FC1-BF22-5379083F3949/data/Applications/17BA56DF-3F65-4498-9A1D-6CEAD0D26CFE/myapp.app/lib/python2.7/config/Makefile (No such file or directory)

**Comment by clowwindy** [comment]
See https://github.com/clowwindy/iOS-Python-Project/issues/3

**Comment by rexzhang** [comment]
fine, it's work. thank you
